# Generated by Django 4.1.3 on 2022-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_as_donor',
            old_name='home',
            new_name='address',
        ),
        migrations.AddField(
            model_name='register_as_donor',
            name='date_of_birth',
            field=models.DateField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='register_as_donor',
            name='sickness',
            field=models.BooleanField(choices=[('HIV', 'HIV'), ('Malaria', 'Malaria')], default=False),
        ),
    ]
