# Generated by Django 4.1.3 on 2022-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0002_rename_home_register_as_donor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_as_donor',
            name='sickness',
            field=models.BooleanField(choices=[('HIV', 'HIV'), ('Malaria', 'Malaria'), ('None', 'None')], default=False),
        ),
    ]
