# Generated by Django 4.1.3 on 2022-11-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0003_alter_register_as_donor_sickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_for_blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('blood_unit', models.CharField(max_length=25, null=True)),
                ('patient_name', models.CharField(max_length=25, null=True)),
                ('purpose', models.CharField(max_length=25, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=25, null=True)),
                ('patient_age', models.CharField(max_length=25, null=True)),
                ('hospital_name', models.CharField(max_length=25, null=True)),
                ('when_need_blood', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=25, null=True)),
                ('details', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='register_as_donor',
            name='sickness',
            field=models.BooleanField(choices=[('HIV', 'HIV'), ('Malaria with in this week', 'Malaria with in this week'), ('None', 'None')], default=False),
        ),
    ]
