# Generated by Django 4.1.3 on 2022-11-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0004_request_for_blood_alter_register_as_donor_sickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_as_donor',
            name='sickness',
            field=models.CharField(choices=[('HIV', 'HIV'), ('Malaria within this week', 'Malaria within this week'), ('None', 'None')], max_length=50),
        ),
    ]
