# Generated by Django 4.1.3 on 2022-11-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0006_chatroom_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
