# Generated by Django 4.1.3 on 2022-11-21 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_system', '0011_alter_chatroom_options_alter_message_chatroom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatroom',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chatroom',
            new_name='room',
        ),
    ]
