# Generated by Django 4.1.3 on 2022-11-23 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_system', '0012_rename_chatroom_room_rename_chatroom_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participats',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
