# Generated by Django 4.1.3 on 2022-11-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_system', '0014_alter_room_participats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participats',
            new_name='participants',
        ),
    ]
